################################################################################
# Automatically-generated file. Do not edit!
# Toolchain: GNU Tools for STM32 (10.3-2021.10)
################################################################################

ELF_SRCS := 
C_UPPER_SRCS := 
CXX_SRCS := 
C++_SRCS := 
OBJ_SRCS := 
S_SRCS := 
CC_SRCS := 
C_SRCS := 
CPP_SRCS := 
S_UPPER_SRCS := 
O_SRCS := 
OBJDUMP_LIST := 
C_UPPER_DEPS := 
S_DEPS := 
C_DEPS := 
CC_DEPS := 
SIZE_OUTPUT := 
C++_DEPS := 
SU_FILES := 
EXECUTABLES := 
OBJS := 
CXX_DEPS := 
MAP_FILES := 
S_UPPER_DEPS := 
CPP_DEPS := 

# Every subdirectory with source files must be described here
SUBDIRS := \
ChibiOS_3.0.5/ext/stdperiph_stm32f4/src \
ChibiOS_3.0.5/os/common/ports/ARM/compilers/GCC \
ChibiOS_3.0.5/os/common/ports/ARMCMx/compilers/GCC \
ChibiOS_3.0.5/os/common/ports/ARMCMx/compilers/IAR \
ChibiOS_3.0.5/os/common/ports/ARMCMx/compilers/RVCT \
ChibiOS_3.0.5/os/common/ports/e200/compilers/GCC \
ChibiOS_3.0.5/os/common/ports/e200/devices/SPC560BCxx \
ChibiOS_3.0.5/os/common/ports/e200/devices/SPC560Bxx \
ChibiOS_3.0.5/os/common/ports/e200/devices/SPC560Dxx \
ChibiOS_3.0.5/os/common/ports/e200/devices/SPC560Pxx \
ChibiOS_3.0.5/os/common/ports/e200/devices/SPC563Mxx \
ChibiOS_3.0.5/os/common/ports/e200/devices/SPC564Axx \
ChibiOS_3.0.5/os/common/ports/e200/devices/SPC56ECxx \
ChibiOS_3.0.5/os/common/ports/e200/devices/SPC56ELxx \
ChibiOS_3.0.5/os/common/ports/e200/devices/SPC57EMxx_HSM \
ChibiOS_3.0.5/os/hal/lib/streams \
ChibiOS_3.0.5/os/hal/osal/nil \
ChibiOS_3.0.5/os/hal/osal/os-less/ARMCMx \
ChibiOS_3.0.5/os/hal/osal/rt \
ChibiOS_3.0.5/os/hal/ports/STM32/LLD/DACv1 \
ChibiOS_3.0.5/os/hal/ports/STM32/LLD/DMAv1 \
ChibiOS_3.0.5/os/hal/ports/STM32/LLD/GPIOv1 \
ChibiOS_3.0.5/os/hal/ports/STM32/LLD/GPIOv2 \
ChibiOS_3.0.5/os/hal/ports/STM32/LLD/I2Cv1 \
ChibiOS_3.0.5/os/hal/ports/STM32/LLD/I2Cv2 \
ChibiOS_3.0.5/os/hal/ports/STM32/LLD/OTGv1 \
ChibiOS_3.0.5/os/hal/ports/STM32/LLD/RTCv1 \
ChibiOS_3.0.5/os/hal/ports/STM32/LLD/RTCv2 \
ChibiOS_3.0.5/os/hal/ports/STM32/LLD/SPIv1 \
ChibiOS_3.0.5/os/hal/ports/STM32/LLD/SPIv2 \
ChibiOS_3.0.5/os/hal/ports/STM32/LLD/TIMv1 \
ChibiOS_3.0.5/os/hal/ports/STM32/LLD/USARTv1 \
ChibiOS_3.0.5/os/hal/ports/STM32/LLD/USARTv2 \
ChibiOS_3.0.5/os/hal/ports/STM32/LLD/USBv1 \
ChibiOS_3.0.5/os/hal/ports/STM32/LLD \
ChibiOS_3.0.5/os/hal/ports/STM32/STM32F0xx \
ChibiOS_3.0.5/os/hal/ports/STM32/STM32F1xx \
ChibiOS_3.0.5/os/hal/ports/STM32/STM32F37x \
ChibiOS_3.0.5/os/hal/ports/STM32/STM32F3xx \
ChibiOS_3.0.5/os/hal/ports/STM32/STM32F4xx \
ChibiOS_3.0.5/os/hal/ports/STM32/STM32L1xx \
ChibiOS_3.0.5/os/hal/ports/common/ARMCMx \
ChibiOS_3.0.5/os/hal/src \
ChibiOS_3.0.5/os/nil/ports/ARMCMx/compilers/GCC \
ChibiOS_3.0.5/os/nil/ports/ARMCMx \
ChibiOS_3.0.5/os/nil/ports/AVR \
ChibiOS_3.0.5/os/nil/ports/e200/compilers/GCC \
ChibiOS_3.0.5/os/nil/ports/e200 \
ChibiOS_3.0.5/os/nil/src \
ChibiOS_3.0.5/os/nil/templates \
ChibiOS_3.0.5/os/rt/ports/ARM \
ChibiOS_3.0.5/os/rt/ports/ARM/compilers/GCC \
ChibiOS_3.0.5/os/rt/ports/ARMCMx \
ChibiOS_3.0.5/os/rt/ports/ARMCMx/cmsis_os \
ChibiOS_3.0.5/os/rt/ports/ARMCMx/compilers/GCC \
ChibiOS_3.0.5/os/rt/ports/ARMCMx/compilers/IAR \
ChibiOS_3.0.5/os/rt/ports/ARMCMx/compilers/RVCT \
ChibiOS_3.0.5/os/rt/ports/AVR \
ChibiOS_3.0.5/os/rt/ports/SIMIA32 \
ChibiOS_3.0.5/os/rt/ports/e200 \
ChibiOS_3.0.5/os/rt/ports/e200/compilers/GCC \
ChibiOS_3.0.5/os/rt/src \
ChibiOS_3.0.5/os/rt/templates \
ChibiOS_3.0.5/os/rt/templates/meta \
ChibiOS_3.0.5/os/various/cpp_wrappers \
ChibiOS_3.0.5/os/various/devices_lib/accel \
ChibiOS_3.0.5/os/various/devices_lib/lcd \
ChibiOS_3.0.5/os/various \
ChibiOS_3.0.5/os/various/fatfs_bindings \
ChibiOS_3.0.5/os/various/lwip_bindings/arch \
ChibiOS_3.0.5/os/various/lwip_bindings \
applications \
applications/er \
applications/finn \
blackmagic \
blackmagic/target \
blackmagic/target/flashstub \
. \
build/410 \
build/410/obj \
comm \
downloads/gcc-arm-none-eabi-7-2018-q2-update/arm-none-eabi/lib/cpu-init \
downloads/gcc-arm-none-eabi-7-2018-q2-update/arm-none-eabi/lib \
downloads/gcc-arm-none-eabi-7-2018-q2-update/arm-none-eabi/lib/hard/cpu-init \
downloads/gcc-arm-none-eabi-7-2018-q2-update/arm-none-eabi/lib/hard \
downloads/gcc-arm-none-eabi-7-2018-q2-update/arm-none-eabi/lib/thumb/cpu-init \
downloads/gcc-arm-none-eabi-7-2018-q2-update/arm-none-eabi/lib/thumb \
downloads/gcc-arm-none-eabi-7-2018-q2-update/arm-none-eabi/lib/thumb/v6-m/cpu-init \
downloads/gcc-arm-none-eabi-7-2018-q2-update/arm-none-eabi/lib/thumb/v6-m \
downloads/gcc-arm-none-eabi-7-2018-q2-update/arm-none-eabi/lib/thumb/v7-ar/cpu-init \
downloads/gcc-arm-none-eabi-7-2018-q2-update/arm-none-eabi/lib/thumb/v7-ar \
downloads/gcc-arm-none-eabi-7-2018-q2-update/arm-none-eabi/lib/thumb/v7-ar/fpv3/hard/cpu-init \
downloads/gcc-arm-none-eabi-7-2018-q2-update/arm-none-eabi/lib/thumb/v7-ar/fpv3/hard \
downloads/gcc-arm-none-eabi-7-2018-q2-update/arm-none-eabi/lib/thumb/v7-ar/fpv3/softfp/cpu-init \
downloads/gcc-arm-none-eabi-7-2018-q2-update/arm-none-eabi/lib/thumb/v7-ar/fpv3/softfp \
downloads/gcc-arm-none-eabi-7-2018-q2-update/arm-none-eabi/lib/thumb/v7-m/cpu-init \
downloads/gcc-arm-none-eabi-7-2018-q2-update/arm-none-eabi/lib/thumb/v7-m \
downloads/gcc-arm-none-eabi-7-2018-q2-update/arm-none-eabi/lib/thumb/v7e-m/cpu-init \
downloads/gcc-arm-none-eabi-7-2018-q2-update/arm-none-eabi/lib/thumb/v7e-m \
downloads/gcc-arm-none-eabi-7-2018-q2-update/arm-none-eabi/lib/thumb/v7e-m/fpv4-sp/hard/cpu-init \
downloads/gcc-arm-none-eabi-7-2018-q2-update/arm-none-eabi/lib/thumb/v7e-m/fpv4-sp/hard \
downloads/gcc-arm-none-eabi-7-2018-q2-update/arm-none-eabi/lib/thumb/v7e-m/fpv4-sp/softfp/cpu-init \
downloads/gcc-arm-none-eabi-7-2018-q2-update/arm-none-eabi/lib/thumb/v7e-m/fpv4-sp/softfp \
downloads/gcc-arm-none-eabi-7-2018-q2-update/arm-none-eabi/lib/thumb/v7e-m/fpv5/hard/cpu-init \
downloads/gcc-arm-none-eabi-7-2018-q2-update/arm-none-eabi/lib/thumb/v7e-m/fpv5/hard \
downloads/gcc-arm-none-eabi-7-2018-q2-update/arm-none-eabi/lib/thumb/v7e-m/fpv5/softfp/cpu-init \
downloads/gcc-arm-none-eabi-7-2018-q2-update/arm-none-eabi/lib/thumb/v7e-m/fpv5/softfp \
downloads/gcc-arm-none-eabi-7-2018-q2-update/arm-none-eabi/lib/thumb/v8-m.base/cpu-init \
downloads/gcc-arm-none-eabi-7-2018-q2-update/arm-none-eabi/lib/thumb/v8-m.base \
downloads/gcc-arm-none-eabi-7-2018-q2-update/arm-none-eabi/lib/thumb/v8-m.main/cpu-init \
downloads/gcc-arm-none-eabi-7-2018-q2-update/arm-none-eabi/lib/thumb/v8-m.main \
downloads/gcc-arm-none-eabi-7-2018-q2-update/arm-none-eabi/lib/thumb/v8-m.main/fpv5/hard/cpu-init \
downloads/gcc-arm-none-eabi-7-2018-q2-update/arm-none-eabi/lib/thumb/v8-m.main/fpv5/hard \
downloads/gcc-arm-none-eabi-7-2018-q2-update/arm-none-eabi/lib/thumb/v8-m.main/fpv5/softfp/cpu-init \
downloads/gcc-arm-none-eabi-7-2018-q2-update/arm-none-eabi/lib/thumb/v8-m.main/fpv5/softfp \
downloads/gcc-arm-none-eabi-7-2018-q2-update/arm-none-eabi/lib/thumb/v8-m.main/fpv5-sp/hard/cpu-init \
downloads/gcc-arm-none-eabi-7-2018-q2-update/arm-none-eabi/lib/thumb/v8-m.main/fpv5-sp/hard \
downloads/gcc-arm-none-eabi-7-2018-q2-update/arm-none-eabi/lib/thumb/v8-m.main/fpv5-sp/softfp/cpu-init \
downloads/gcc-arm-none-eabi-7-2018-q2-update/arm-none-eabi/lib/thumb/v8-m.main/fpv5-sp/softfp \
downloads/gcc-arm-none-eabi-7-2018-q2-update/lib/gcc/arm-none-eabi/7.3.1 \
downloads/gcc-arm-none-eabi-7-2018-q2-update/lib/gcc/arm-none-eabi/7.3.1/hard \
downloads/gcc-arm-none-eabi-7-2018-q2-update/lib/gcc/arm-none-eabi/7.3.1/thumb \
downloads/gcc-arm-none-eabi-7-2018-q2-update/lib/gcc/arm-none-eabi/7.3.1/thumb/v6-m \
downloads/gcc-arm-none-eabi-7-2018-q2-update/lib/gcc/arm-none-eabi/7.3.1/thumb/v7-ar \
downloads/gcc-arm-none-eabi-7-2018-q2-update/lib/gcc/arm-none-eabi/7.3.1/thumb/v7-ar/fpv3/hard \
downloads/gcc-arm-none-eabi-7-2018-q2-update/lib/gcc/arm-none-eabi/7.3.1/thumb/v7-ar/fpv3/softfp \
downloads/gcc-arm-none-eabi-7-2018-q2-update/lib/gcc/arm-none-eabi/7.3.1/thumb/v7-m \
downloads/gcc-arm-none-eabi-7-2018-q2-update/lib/gcc/arm-none-eabi/7.3.1/thumb/v7e-m \
downloads/gcc-arm-none-eabi-7-2018-q2-update/lib/gcc/arm-none-eabi/7.3.1/thumb/v7e-m/fpv4-sp/hard \
downloads/gcc-arm-none-eabi-7-2018-q2-update/lib/gcc/arm-none-eabi/7.3.1/thumb/v7e-m/fpv4-sp/softfp \
downloads/gcc-arm-none-eabi-7-2018-q2-update/lib/gcc/arm-none-eabi/7.3.1/thumb/v7e-m/fpv5/hard \
downloads/gcc-arm-none-eabi-7-2018-q2-update/lib/gcc/arm-none-eabi/7.3.1/thumb/v7e-m/fpv5/softfp \
downloads/gcc-arm-none-eabi-7-2018-q2-update/lib/gcc/arm-none-eabi/7.3.1/thumb/v8-m.base \
downloads/gcc-arm-none-eabi-7-2018-q2-update/lib/gcc/arm-none-eabi/7.3.1/thumb/v8-m.main \
downloads/gcc-arm-none-eabi-7-2018-q2-update/lib/gcc/arm-none-eabi/7.3.1/thumb/v8-m.main/fpv5/hard \
downloads/gcc-arm-none-eabi-7-2018-q2-update/lib/gcc/arm-none-eabi/7.3.1/thumb/v8-m.main/fpv5/softfp \
downloads/gcc-arm-none-eabi-7-2018-q2-update/lib/gcc/arm-none-eabi/7.3.1/thumb/v8-m.main/fpv5-sp/hard \
downloads/gcc-arm-none-eabi-7-2018-q2-update/lib/gcc/arm-none-eabi/7.3.1/thumb/v8-m.main/fpv5-sp/softfp \
downloads/gcc-arm-none-eabi-7-2018-q2-update/share/gcc-arm-none-eabi/samples/src/cpp \
downloads/gcc-arm-none-eabi-7-2018-q2-update/share/gcc-arm-none-eabi/samples/src/fpin \
downloads/gcc-arm-none-eabi-7-2018-q2-update/share/gcc-arm-none-eabi/samples/src/fpout \
downloads/gcc-arm-none-eabi-7-2018-q2-update/share/gcc-arm-none-eabi/samples/src/minimum \
downloads/gcc-arm-none-eabi-7-2018-q2-update/share/gcc-arm-none-eabi/samples/src/multiram \
downloads/gcc-arm-none-eabi-7-2018-q2-update/share/gcc-arm-none-eabi/samples/src/qemu \
downloads/gcc-arm-none-eabi-7-2018-q2-update/share/gcc-arm-none-eabi/samples/src/retarget \
downloads/gcc-arm-none-eabi-7-2018-q2-update/share/gcc-arm-none-eabi/samples/src/semihost \
downloads/gcc-arm-none-eabi-7-2018-q2-update/share/gcc-arm-none-eabi/samples/startup \
driver \
driver/lora \
driver/nrf \
encoder \
hwconf/Ubox/100v \
hwconf/Ubox/75v \
hwconf \
hwconf/luna \
hwconf/other/Little_FOCer \
hwconf/other \
hwconf/other/vesc4 \
hwconf/stormcore/100D \
hwconf/stormcore/100S \
hwconf/stormcore/60D \
hwconf/teamtriforceuk/a200s \
hwconf/teamtriforceuk/a50s \
hwconf/trampa/100_250 \
hwconf/trampa/100_500 \
hwconf/trampa/140_300 \
hwconf/trampa/60_75 \
hwconf/trampa/60_alva \
hwconf/trampa/75_300 \
hwconf/trampa/75_300_R34 \
hwconf/trampa/hd \
hwconf/trampa/vesc6 \
hwconf/trampa/vesc_edu \
imu/BMI160_driver \
imu/Fusion/Examples \
imu/Fusion \
imu \
libcanard \
libcanard/dsdl/uavcan/equipment/esc \
libcanard/dsdl/uavcan/equipment/power \
libcanard/dsdl/uavcan/protocol/file \
libcanard/dsdl/uavcan/protocol/param \
libcanard/dsdl/uavcan/protocol \
libcanard/dsdl/vesc \
lispBM/c_libs/examples/extension \
lispBM/c_libs/examples/ssd1306 \
lispBM/c_libs/examples/thread \
lispBM/c_libs/examples/ws2812 \
lispBM/c_libs/stdperiph_stm32f4/src \
lispBM/lispBM/benchmarks/bench_chibi \
lispBM/lispBM/chibios-examples/repl-ChibiOS \
lispBM/lispBM/chibios-examples/xmas_dac \
lispBM/lispBM/esp-examples/repl/main \
lispBM/lispBM/examples \
lispBM/lispBM/old/repl-cps-zynq \
lispBM/lispBM/old/repl-ec \
lispBM/lispBM/old/repl-esp-idf/main \
lispBM/lispBM/platform/chibios/src \
lispBM/lispBM/platform/freertos/src \
lispBM/lispBM/platform/linux/src \
lispBM/lispBM/platform/zephyr/src \
lispBM/lispBM/repl \
lispBM/lispBM/sdlrepl \
lispBM/lispBM/src \
lispBM/lispBM/src/extensions \
lispBM/lispBM/src/visual \
lispBM/lispBM/tests \
lispBM/lispBM/zephyr-examples/repl-zephyr/src \
lispBM/lispBM/zephyr-examples/repl-zephyr \
lispBM \
motor \
qmlui/app \
qmlui/hw \
qmlui \
tests/float_serialization \
tests/packet_recovery \
tests/utils_math \
tools/gcc-arm-none-eabi-7-2018-q2-update/arm-none-eabi/lib/cpu-init \
tools/gcc-arm-none-eabi-7-2018-q2-update/arm-none-eabi/lib \
tools/gcc-arm-none-eabi-7-2018-q2-update/arm-none-eabi/lib/hard/cpu-init \
tools/gcc-arm-none-eabi-7-2018-q2-update/arm-none-eabi/lib/hard \
tools/gcc-arm-none-eabi-7-2018-q2-update/arm-none-eabi/lib/thumb/cpu-init \
tools/gcc-arm-none-eabi-7-2018-q2-update/arm-none-eabi/lib/thumb \
tools/gcc-arm-none-eabi-7-2018-q2-update/arm-none-eabi/lib/thumb/v6-m/cpu-init \
tools/gcc-arm-none-eabi-7-2018-q2-update/arm-none-eabi/lib/thumb/v6-m \
tools/gcc-arm-none-eabi-7-2018-q2-update/arm-none-eabi/lib/thumb/v7-ar/cpu-init \
tools/gcc-arm-none-eabi-7-2018-q2-update/arm-none-eabi/lib/thumb/v7-ar \
tools/gcc-arm-none-eabi-7-2018-q2-update/arm-none-eabi/lib/thumb/v7-ar/fpv3/hard/cpu-init \
tools/gcc-arm-none-eabi-7-2018-q2-update/arm-none-eabi/lib/thumb/v7-ar/fpv3/hard \
tools/gcc-arm-none-eabi-7-2018-q2-update/arm-none-eabi/lib/thumb/v7-ar/fpv3/softfp/cpu-init \
tools/gcc-arm-none-eabi-7-2018-q2-update/arm-none-eabi/lib/thumb/v7-ar/fpv3/softfp \
tools/gcc-arm-none-eabi-7-2018-q2-update/arm-none-eabi/lib/thumb/v7-m/cpu-init \
tools/gcc-arm-none-eabi-7-2018-q2-update/arm-none-eabi/lib/thumb/v7-m \
tools/gcc-arm-none-eabi-7-2018-q2-update/arm-none-eabi/lib/thumb/v7e-m/cpu-init \
tools/gcc-arm-none-eabi-7-2018-q2-update/arm-none-eabi/lib/thumb/v7e-m \
tools/gcc-arm-none-eabi-7-2018-q2-update/arm-none-eabi/lib/thumb/v7e-m/fpv4-sp/hard/cpu-init \
tools/gcc-arm-none-eabi-7-2018-q2-update/arm-none-eabi/lib/thumb/v7e-m/fpv4-sp/hard \
tools/gcc-arm-none-eabi-7-2018-q2-update/arm-none-eabi/lib/thumb/v7e-m/fpv4-sp/softfp/cpu-init \
tools/gcc-arm-none-eabi-7-2018-q2-update/arm-none-eabi/lib/thumb/v7e-m/fpv4-sp/softfp \
tools/gcc-arm-none-eabi-7-2018-q2-update/arm-none-eabi/lib/thumb/v7e-m/fpv5/hard/cpu-init \
tools/gcc-arm-none-eabi-7-2018-q2-update/arm-none-eabi/lib/thumb/v7e-m/fpv5/hard \
tools/gcc-arm-none-eabi-7-2018-q2-update/arm-none-eabi/lib/thumb/v7e-m/fpv5/softfp/cpu-init \
tools/gcc-arm-none-eabi-7-2018-q2-update/arm-none-eabi/lib/thumb/v7e-m/fpv5/softfp \
tools/gcc-arm-none-eabi-7-2018-q2-update/arm-none-eabi/lib/thumb/v8-m.base/cpu-init \
tools/gcc-arm-none-eabi-7-2018-q2-update/arm-none-eabi/lib/thumb/v8-m.base \
tools/gcc-arm-none-eabi-7-2018-q2-update/arm-none-eabi/lib/thumb/v8-m.main/cpu-init \
tools/gcc-arm-none-eabi-7-2018-q2-update/arm-none-eabi/lib/thumb/v8-m.main \
tools/gcc-arm-none-eabi-7-2018-q2-update/arm-none-eabi/lib/thumb/v8-m.main/fpv5/hard/cpu-init \
tools/gcc-arm-none-eabi-7-2018-q2-update/arm-none-eabi/lib/thumb/v8-m.main/fpv5/hard \
tools/gcc-arm-none-eabi-7-2018-q2-update/arm-none-eabi/lib/thumb/v8-m.main/fpv5/softfp/cpu-init \
tools/gcc-arm-none-eabi-7-2018-q2-update/arm-none-eabi/lib/thumb/v8-m.main/fpv5/softfp \
tools/gcc-arm-none-eabi-7-2018-q2-update/arm-none-eabi/lib/thumb/v8-m.main/fpv5-sp/hard/cpu-init \
tools/gcc-arm-none-eabi-7-2018-q2-update/arm-none-eabi/lib/thumb/v8-m.main/fpv5-sp/hard \
tools/gcc-arm-none-eabi-7-2018-q2-update/arm-none-eabi/lib/thumb/v8-m.main/fpv5-sp/softfp/cpu-init \
tools/gcc-arm-none-eabi-7-2018-q2-update/arm-none-eabi/lib/thumb/v8-m.main/fpv5-sp/softfp \
tools/gcc-arm-none-eabi-7-2018-q2-update/lib/gcc/arm-none-eabi/7.3.1 \
tools/gcc-arm-none-eabi-7-2018-q2-update/lib/gcc/arm-none-eabi/7.3.1/hard \
tools/gcc-arm-none-eabi-7-2018-q2-update/lib/gcc/arm-none-eabi/7.3.1/thumb \
tools/gcc-arm-none-eabi-7-2018-q2-update/lib/gcc/arm-none-eabi/7.3.1/thumb/v6-m \
tools/gcc-arm-none-eabi-7-2018-q2-update/lib/gcc/arm-none-eabi/7.3.1/thumb/v7-ar \
tools/gcc-arm-none-eabi-7-2018-q2-update/lib/gcc/arm-none-eabi/7.3.1/thumb/v7-ar/fpv3/hard \
tools/gcc-arm-none-eabi-7-2018-q2-update/lib/gcc/arm-none-eabi/7.3.1/thumb/v7-ar/fpv3/softfp \
tools/gcc-arm-none-eabi-7-2018-q2-update/lib/gcc/arm-none-eabi/7.3.1/thumb/v7-m \
tools/gcc-arm-none-eabi-7-2018-q2-update/lib/gcc/arm-none-eabi/7.3.1/thumb/v7e-m \
tools/gcc-arm-none-eabi-7-2018-q2-update/lib/gcc/arm-none-eabi/7.3.1/thumb/v7e-m/fpv4-sp/hard \
tools/gcc-arm-none-eabi-7-2018-q2-update/lib/gcc/arm-none-eabi/7.3.1/thumb/v7e-m/fpv4-sp/softfp \
tools/gcc-arm-none-eabi-7-2018-q2-update/lib/gcc/arm-none-eabi/7.3.1/thumb/v7e-m/fpv5/hard \
tools/gcc-arm-none-eabi-7-2018-q2-update/lib/gcc/arm-none-eabi/7.3.1/thumb/v7e-m/fpv5/softfp \
tools/gcc-arm-none-eabi-7-2018-q2-update/lib/gcc/arm-none-eabi/7.3.1/thumb/v8-m.base \
tools/gcc-arm-none-eabi-7-2018-q2-update/lib/gcc/arm-none-eabi/7.3.1/thumb/v8-m.main \
tools/gcc-arm-none-eabi-7-2018-q2-update/lib/gcc/arm-none-eabi/7.3.1/thumb/v8-m.main/fpv5/hard \
tools/gcc-arm-none-eabi-7-2018-q2-update/lib/gcc/arm-none-eabi/7.3.1/thumb/v8-m.main/fpv5/softfp \
tools/gcc-arm-none-eabi-7-2018-q2-update/lib/gcc/arm-none-eabi/7.3.1/thumb/v8-m.main/fpv5-sp/hard \
tools/gcc-arm-none-eabi-7-2018-q2-update/lib/gcc/arm-none-eabi/7.3.1/thumb/v8-m.main/fpv5-sp/softfp \
tools/gcc-arm-none-eabi-7-2018-q2-update/share/gcc-arm-none-eabi/samples/src/cpp \
tools/gcc-arm-none-eabi-7-2018-q2-update/share/gcc-arm-none-eabi/samples/src/fpin \
tools/gcc-arm-none-eabi-7-2018-q2-update/share/gcc-arm-none-eabi/samples/src/fpout \
tools/gcc-arm-none-eabi-7-2018-q2-update/share/gcc-arm-none-eabi/samples/src/minimum \
tools/gcc-arm-none-eabi-7-2018-q2-update/share/gcc-arm-none-eabi/samples/src/multiram \
tools/gcc-arm-none-eabi-7-2018-q2-update/share/gcc-arm-none-eabi/samples/src/qemu \
tools/gcc-arm-none-eabi-7-2018-q2-update/share/gcc-arm-none-eabi/samples/src/retarget \
tools/gcc-arm-none-eabi-7-2018-q2-update/share/gcc-arm-none-eabi/samples/src/semihost \
tools/gcc-arm-none-eabi-7-2018-q2-update/share/gcc-arm-none-eabi/samples/startup \
util \
util/lzo \

